

export interface MetaTag {
  name?: string;
  property?: string;
  content: string;
  [key: string]: any;
}

export interface HeadMeta {
  title?: string;
  description?: string;
  keywords?: string[];
  canonical?: string;
  meta?: MetaTag[];
  links?: { rel: string; href: string; [key: string]: any }[];
}

export interface SitemapEntry {
  path?: string;
  lastmod?: string;
  changefreq?: 'always' | 'hourly' | 'daily' | 'weekly' | 'monthly' | 'yearly' | 'never';
  priority?: number;
}

export const metadata: HeadMeta = {
title: "My Page",
description: "Page description",
keywords: ["my", "page"]
};

export const sitemap:SitemapEntry = {
priority: 0.8,
changefreq: 'weekly'
};

export default function Page() {
return (
  <main>
    <h1>Page Content</h1>
    <p>This is a page automatically generated by WouterFS</p>
  </main>
);
}
